name: Go Tests

# TODO
# Docs
# Project Tests
# switch to main branch again

on:
  workflow_call:
    inputs:
      # <--------------- GENERAL GO OPTIONS ---------------->
      go-version:
        required: false
        type: string
        description: "Select the version of go to use. Accepts https://github.com/npm/node-semver"
        default: "^1.17"

jobs:
  unit-tests:
    name: demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}

      - name: Install Dependencies
        run: go get -d
